Fix duplicate trait import
```
error[E0252]: the name `Cb58Encodable` is defined multiple times
  --> apps/avalanche/src/transactions/P_chain/validator.rs:41:9
   |
38 |     use crate::encode::cb58::Cb58Encodable;
   |         ---------------------------------- previous import of the trait `Cb58Encodable` here
...
41 |     use crate::encode::cb58::Cb58Encodable;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Cb58Encodable` reimported here
   |
   = note: `Cb58Encodable` must be defined only once in the type namespace of this module
```